#include "../../uCGUI391/Core/GUI_ErrorOut.c"
#include "../../uCGUI391/Core/LCD_RotateCW.c"
#include "../../uCGUI391/Core/GUI_GetBitmapPixelColor.c"
#include "../../uCGUI391/Core/GUI_GetBitmapPixelIndex.c"
#include "../../uCGUI391/Core/GUI_GetClientRect.c"
#include "../../uCGUI391/Core/GUI_GetColor.c"
#include "../../uCGUI391/Core/GUI_GetDispPos.c"
#include "../../uCGUI391/Core/GUI_GetFont.c"
#include "../../uCGUI391/Core/GUI_GetFontInfo.c"
#include "../../uCGUI391/Core/GUI_GetFontSizeY.c"
#include "../../uCGUI391/Core/GUI_GetLineStyle.c"
#include "../../uCGUI391/Core/GUI_GetStringDistX.c"
#include "../../uCGUI391/Core/GUI_GetTextAlign.c"
#include "../../uCGUI391/Core/GUI_GetTextExtend.c"
#include "../../uCGUI391/Core/GUI_GetTextMode.c"
#include "../../uCGUI391/Core/GUI_GetVersionString.c"
#include "../../uCGUI391/Core/GUI_GetYSizeOfFont.c"



#pragma GCC diagnostic ignored "-Wmissing-field-initializers"

#include "../../uCGUI391/Core/GUI_CursorArrowL.c"
#include "../../uCGUI391/Core/GUI_CursorArrowLI.c"
#include "../../uCGUI391/Core/GUI_CursorArrowLPx.c"
#include "../../uCGUI391/Core/GUI_CursorArrowM.c"
#include "../../uCGUI391/Core/GUI_CursorArrowMI.c"
#include "../../uCGUI391/Core/GUI_CursorArrowMPx.c"
#include "../../uCGUI391/Core/GUI_CursorArrowS.c"
#include "../../uCGUI391/Core/GUI_CursorArrowSI.c"
#include "../../uCGUI391/Core/GUI_CursorArrowSPx.c"
#include "../../uCGUI391/Core/GUI_CursorCrossL.c"
#include "../../uCGUI391/Core/GUI_CursorCrossLI.c"
#include "../../uCGUI391/Core/GUI_CursorCrossLPx.c"
#include "../../uCGUI391/Core/GUI_CursorCrossM.c"
#include "../../uCGUI391/Core/GUI_CursorCrossMI.c"
#include "../../uCGUI391/Core/GUI_CursorCrossMPx.c"
#include "../../uCGUI391/Core/GUI_CursorCrossS.c"
#include "../../uCGUI391/Core/GUI_CursorCrossSI.c"
#include "../../uCGUI391/Core/GUI_CursorCrossSPx.c"
#include "../../uCGUI391/Core/GUI_CursorHeaderM.c"
#include "../../uCGUI391/Core/GUI_CursorHeaderMI.c"
#include "../../uCGUI391/Core/GUI_CursorHeaderMPx.c"
#include "../../uCGUI391/Core/GUI_CursorPal.c"