#include "../../uCGUI391/MemDev/GUIDEV.c"
#include "../../uCGUI391/MemDev/GUIDEV_AA.c"
#include "../../uCGUI391/MemDev/GUIDEV_Auto.c"
#include "../../uCGUI391/MemDev/GUIDEV_Banding.c"
#include "../../uCGUI391/MemDev/GUIDEV_Clear.c"
#include "../../uCGUI391/MemDev/GUIDEV_CmpWithLCD.c"
#include "../../uCGUI391/MemDev/GUIDEV_CopyFromLCD.c"
#include "../../uCGUI391/MemDev/GUIDEV_CreateFixed.c"
#include "../../uCGUI391/MemDev/GUIDEV_GetDataPtr.c"
#include "../../uCGUI391/MemDev/GUIDEV_GetXSize.c"
#include "../../uCGUI391/MemDev/GUIDEV_GetYSize.c"

#pragma GCC diagnostic ignored "-Wmissing-field-initializers"

#include "../../uCGUI391/MemDev/GUIDEV_Measure.c"
#include "../../uCGUI391/MemDev/GUIDEV_ReduceYSize.c"
#include "../../uCGUI391/MemDev/GUIDEV_SetOrg.c"
#include "../../uCGUI391/MemDev/GUIDEV_Usage.c"
#include "../../uCGUI391/MemDev/GUIDEV_Write.c"
#include "../../uCGUI391/MemDev/GUIDEV_XY2PTR.c"
